# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Conreq < Formula
  desc "CLI tool to send concurrent HTTP requests for API behavior verification"
  homepage "https://github.com/shiroemons/conreq"
  version "0.1.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shiroemons/conreq/releases/download/v0.1.6/conreq_Darwin_x86_64.tar.gz"
      sha256 "c9847785cb1f099b8d4ccbd5a3ed828a6b0c22a0c608cd873589af71aea9f235"

      def install
        bin.install "conreq"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shiroemons/conreq/releases/download/v0.1.6/conreq_Darwin_arm64.tar.gz"
      sha256 "cf72d238fb5287cf7f00ebbbc5f5dceb74ca63b93e118f19852d1bac1f793d9f"

      def install
        bin.install "conreq"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/shiroemons/conreq/releases/download/v0.1.6/conreq_Linux_x86_64.tar.gz"
      sha256 "ee4aa7f750b1361ca4f6a3daef4061db4b07ef8d4d17defbda0dfbfa187b6a20"
      def install
        bin.install "conreq"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/shiroemons/conreq/releases/download/v0.1.6/conreq_Linux_arm64.tar.gz"
      sha256 "b23774a218b80caf262d1f3e957a654ac56b28cadb84fb84d0002242b492b75d"
      def install
        bin.install "conreq"
      end
    end
  end

  test do
    system "#{bin}/conreq", "version"
  end
end
