# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Conreq < Formula
  desc "CLI tool to send concurrent HTTP requests for API behavior verification"
  homepage "https://github.com/shiroemons/conreq"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shiroemons/conreq/releases/download/v0.2.0/conreq_Darwin_x86_64.tar.gz"
      sha256 "7ce56e514ba8053c5d681499dd590fc31b15accde52f26d2ac104771986154d1"

      def install
        bin.install "conreq"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shiroemons/conreq/releases/download/v0.2.0/conreq_Darwin_arm64.tar.gz"
      sha256 "dce26190acc14c93f7a0181a15c64e5fd80d2f1ca6c4fd7eb51842f395cde32d"

      def install
        bin.install "conreq"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/shiroemons/conreq/releases/download/v0.2.0/conreq_Linux_x86_64.tar.gz"
      sha256 "8b2b2bfbb568b303df48ca86d2d9a368d8a8d83add91ff5bb560123f9fa64ea0"
      def install
        bin.install "conreq"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/shiroemons/conreq/releases/download/v0.2.0/conreq_Linux_arm64.tar.gz"
      sha256 "59ee87c349bdd3331aba6396555b8ab1244eb7215196bf81ed2db091729ccefb"
      def install
        bin.install "conreq"
      end
    end
  end

  test do
    system "#{bin}/conreq", "version"
  end
end
